#
# This is the Docker image that gets published to GitHub.
#
# Goreleaser takes care of building the binary.
#
FROM alpine:3@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

COPY publiccode-validator-api /usr/local/bin/publiccode-validator-api

ENTRYPOINT ["/usr/local/bin/publiccode-validator-api"]
